openapi: 3.0.0

info:
  title: TH-Movie Mentor API
  description: This API provides information about Thai movies including details about specific movies.
  version: 2.0.0

servers:
  - url: http://127.0.0.1:8080/TH-Movie

paths:
  /movies:
    get:
      summary: Get a list of all movies
      operationId: controller.get_movies
      responses:
        "200":
          description: An array of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"

  /movies/{movie_id}:
    get:
      summary: Get information about a specific movie
      operationId: controller.get_movie_information
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A movie, including actors and platform availability
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieInformation"

  /movies/actor/{actor_id}:
    get:
      summary: Get a list of movies starring a specific actor
      operationId: controller.get_movies_by_actor
      parameters:
        - in: path
          name: actor_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: An array of movies starring a specific actor
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Actor"

  /movies/year/{year}:
    get:
      summary: Get a list of movies released in a specific year
      operationId: controller.get_movies_by_year
      parameters:
        - in: path
          name: year
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: An array of movies from a specific year
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"

  /movies/genre/{genre_id}:
    get:
      summary: Get a list of movies in a specific genre
      operationId: controller.get_movies_by_genre
      parameters:
        - in: path
          name: genre_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: An array of movies by genre
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"

  /movies/age/{age}:
    get:
      summary: Get a list of movies popular with a specific age
      operationId: controller.get_movies_by_age
      parameters:
        - in: path
          name: age
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: An array of movies popular with a specific age
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"

  /movies/gender/{gender}:
    get:
      summary: Get a list of movies popular with a specific gender
      operationId: controller.get_movies_by_gender
      parameters:
        - in: path
          name: gender
          required: true
          schema:
            type: string
            enum: [male, female, other]
      responses:
        "200":
          description: An array of movies popular with a specific gender
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"

  /movies/gender/{gender}/age/{age}:
    get:
      summary: Get a list of movies popular with a specific gender and age
      operationId: controller.get_movies_by_gender_age
      parameters:
        - in: path
          name: gender
          required: true
          schema:
            type: string
            enum: [male, female, other]
        - in: path
          name: age
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: An array of movies popular with a specific gender and age
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"

  /movies/application/{platform_id}:
    get:
      summary: Get a list of movies available on a specific platform/application
      operationId: controller.get_movies_by_platform
      parameters:
        - in: path
          name: platform_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: An array of movies available on a specific platform/application
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Movie"

  /movies/{movie_id}/platform:
    get:
      summary: Get a list of platforms/applications where a specific movie is available
      operationId: controller.get_platforms_for_movie
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of platforms/applications for a specific movie
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Platform"

components:
  schemas:
    Movie:
      type: object
      properties:
        movie_id:
          type: string
        title_th:
          type: string
        title_en:
          type: string

    Actor:
      type: object
      properties:
        actor_id:
          type: string
        nickname_th:
          type: string
        fullname_th:
          type: string
        nickname_en:
          type: string
        fullname_en:
          type: string

    Genre:
      type: object
      properties:
        genre_id:
          type: string
        genre_name:
          type: string

    Platform:
      type: object
      properties:
        platform_id:
          type: string
        platform_name:
          type: string

    MovieInformation:
      type: object
      properties:
        movie_id:
          type: string
        title_th:
          type: string
        title_en:
          type: string
        release_year:
          type: integer
        actors:
          type: array
          items:
            $ref: "#/components/schemas/Actor"
        genres:
          type: array
          items:
            $ref: "#/components/schemas/Genre"
        platforms:
          type: array
          items:
            $ref: "#/components/schemas/Platform"

