# Generated by Django 4.1 on 2024-05-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THMovie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='available',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='available',
            old_name='platform',
            new_name='platform_id',
        ),
        migrations.RenameField(
            model_name='moviegenre',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='moviegenre',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='actor',
            new_name='actor_id',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.AddField(
            model_name='response',
            name='actor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='THMovie.actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='satisfaction',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
