# Generated by Django 4.2.13 on 2024-05-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("THMovie", "0002_rename_movie_available_movie_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="id",
        ),
        migrations.AddField(
            model_name="response",
            name="response_id",
            field=models.CharField(
                default=1, max_length=100, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
