# Generated by Django 4.2.13 on 2024-05-11 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("THMovie", "0003_remove_response_id_response_response_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="available",
            old_name="movie_id",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="available",
            old_name="platform_id",
            new_name="platform",
        ),
        migrations.RenameField(
            model_name="moviegenre",
            old_name="genre_id",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="moviegenre",
            old_name="movie_id",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="play",
            old_name="actor_id",
            new_name="actor",
        ),
        migrations.RenameField(
            model_name="play",
            old_name="movie_id",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="response",
            old_name="actor_id",
            new_name="actor",
        ),
        migrations.RenameField(
            model_name="response",
            old_name="movie_id",
            new_name="movie",
        ),
    ]
